
 
use_frameworks!
use_modular_headers!
inhibit_all_warnings!

target 'OpenIMSDKUIKit_Example' do
  pod 'OUICore', :path => '../'
  pod 'OUICoreView', :path => '../'
  pod 'OUIIM', :path => '../'
  pod 'OUICalling', :path => '../'
  pod 'InputBarAccessoryView', :path => '../3rd'
  pod 'ZLPhotoBrowser', :path => '../3rd'
  pod 'ZFPlayer', :path => '../3rd'
  pod 'AlamofireNetworkActivityLogger', :path => '../3rd'  
  
  pod 'Localize-Swift', '~> 3.2'
  pod 'RxGesture', '~> 4.0.4'
  pod 'ProgressHUD', :git => 'https://github.com/std-s/ProgressHUD.git'
  pod 'Lantern', :git => 'https://github.com/std-s/Lantern.git'
  pod 'MMBAlertsPickers', :git => 'https://github.com/std-s/MMBAlertsPickers.git'
  pod 'SGCodeTextField'
  pod 'JXSegmentedView'
    
  pod 'Firebase/Core', '11.12.0'
  pod 'Firebase/Messaging', '11.12.0'
end

post_install do |installer|
  app_project = Xcodeproj::Project.open('OpenIMSDKUIKit.xcodeproj')
    app_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-D', 'COCOAPODS', '-D', 'ENABLE_CALL'
          ]
        end
    end
  app_project.save

  installer.pods_project.build_configurations.each do |config|
    config.build_settings.keys.each do |key|
      config.build_settings.delete(key) if key.include?('EXCLUDED_ARCHS')
    end
  end
  
 installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
          config.build_settings.keys.each do |key|
            config.build_settings.delete(key) if key.include?('EXCLUDED_ARCHS')
          end
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
                
          if target.name == 'OUIIM'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',
            '-D', 'COCOAPODS',
            '-D', 'ENABLE_CALL',
            ]
          end
          
          if target.name == 'OUICore'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',
            '-D', 'COCOAPODS',
            ]
          end

          if target.name == 'OUICoreView'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',
            '-D', 'COCOAPODS',
            ]
          end
    end
  end

  simulator_xcconfig_removals = {
    'FRAMEWORK_SEARCH_PATHS' => [
      '"${PODS_ROOT}/FirebaseAnalytics/Frameworks"',
      '"${PODS_ROOT}/GoogleAppMeasurement/Frameworks"',
      '"${PODS_XCFRAMEWORKS_BUILD_DIR}/FirebaseAnalytics/AdIdSupport"',
      '"${PODS_XCFRAMEWORKS_BUILD_DIR}/GoogleAppMeasurement/AdIdSupport"',
      '"${PODS_XCFRAMEWORKS_BUILD_DIR}/GoogleAppMeasurement/WithoutAdIdSupport"',
    ],
    'OTHER_CFLAGS' => [
      '-iframework "${PODS_ROOT}/FirebaseAnalytics/Frameworks"',
      '-iframework "${PODS_ROOT}/GoogleAppMeasurement/Frameworks"',
      '-iframework "${PODS_XCFRAMEWORKS_BUILD_DIR}/FirebaseAnalytics/AdIdSupport"',
      '-iframework "${PODS_XCFRAMEWORKS_BUILD_DIR}/GoogleAppMeasurement/AdIdSupport"',
      '-iframework "${PODS_XCFRAMEWORKS_BUILD_DIR}/GoogleAppMeasurement/WithoutAdIdSupport"',
    ],
    'OTHER_LDFLAGS' => [
      '-framework "FirebaseAnalytics"',
      '-framework "GoogleAppMeasurement"',
      '-framework "GoogleAppMeasurementIdentitySupport"',
    ],
    'OTHER_MODULE_VERIFIER_FLAGS' => [
      '"-F${PODS_CONFIGURATION_BUILD_DIR}/Firebase"',
      '"-F${PODS_CONFIGURATION_BUILD_DIR}/FirebaseAnalytics"',
      '"-F${PODS_CONFIGURATION_BUILD_DIR}/GoogleAppMeasurement"',
    ],
  }

  Dir.glob('Pods/Target Support Files/**/*.xcconfig').each do |xcconfig_path|
    next unless File.file?(xcconfig_path)

    content = File.read(xcconfig_path)
    cleaned = content
    cleaned = cleaned.lines.reject { |line| line.include?('EXCLUDED_ARCHS[sdk=iphonesimulator*]') }.join

    simulator_xcconfig_removals.each_key do |setting|
      cleaned = cleaned.lines.reject { |line| line.start_with?("#{setting}[sdk=iphonesimulator*] =") }.join
    end

    simulator_xcconfig_removals.each do |setting, fragments|
      next unless cleaned.include?("#{setting} =")

      rewritten_lines = []
      cleaned.each_line do |line|
        rewritten_lines << line
        next unless line.start_with?("#{setting} =")

        sim_line = line.sub("#{setting} =", "#{setting}[sdk=iphonesimulator*] =")
        sim_line = sim_line.sub('$(inherited) ', '').sub('$(inherited)', '')
        fragments.each do |fragment|
          sim_line = sim_line.gsub(fragment, '')
        end
        sim_line = sim_line.gsub(/[ \t]+/, ' ').gsub(' )', ')').rstrip + "\n"
        rewritten_lines << sim_line
      end
      cleaned = rewritten_lines.join
    end

    File.write(xcconfig_path, cleaned) if cleaned != content
  end
end
